 
version: '3.7'

services:
    php-httpd:
        image: php:7.4-apache
        ports:
            - 80:80
        volumes:
            - "./public:/var/www/html"
            - "./apache2/conf/sites-available:/etc/apache2/sites-available"
            - "./apache2/conf/sites-enabled:/etc/apache2/sites-enabled"
            - "./apache2/log/:/var/log/apache2/"

    mariadb:
        image: mariadb:latest
        volumes:
            - mariadb-volume:/var/lib/mysql
        environment:
            TZ: "Europe/Paris"
            MYSQL_ALLOW_EMPTY_PASSWORD: "no"
            MYSQL_ROOT_PASSWORD: "rootpwd"
            MYSQL_USER: 'testuser'
            MYSQL_PASSWORD: 'testpassword'
            MYSQL_DATABASE: 'testdb'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - 'mariadb:db'
        ports:
            - 8081:80

volumes:
    mariadb-volume:
